# Generated by Django 4.2.1 on 2023-05-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_promotion_product_promotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
