# Generated by Django 4.2.1 on 2023-05-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delete_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='expiration_date',
            new_name='end_date',
        ),
    ]
